name:                calendar-up-next
version:             0.1.0.0
github:              "pascalw/calendar-up-next"
license:             MIT
author:              "Pascal Widdershoven"
maintainer:          "hello@pascalw.me"
copyright:           "2018 Pascal Widdershoven"

extra-source-files:
- README.md

description:         Please see the README on Github at <https://github.com/pascalw/calendar-up-next#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- lens
- time
- aeson
- lens-aeson
- google-oauth2-jwt == 0.3.0
- wreq == 0.5.2.1
- string-conversions
- optparse-applicative == 0.14.2.0

default-extensions:
  - OverloadedStrings

library:
  source-dirs: src

executables:
  calendar-up-next:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall -Werror
    dependencies:
    - calendar-up-next

tests:
  calendar-up-next-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - calendar-up-next
